# Generated by Django 4.2.1 on 2023-05-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0003_alter_usuario_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.IntegerField(null=True),
        ),
    ]
